/**
 * Embedding-equivalence smoke test (v0.1.1 locked decision #14).
 *
 * Purpose: verify that OpenRouter's openai/text-embedding-3-small returns
 * numerically equivalent vectors to direct OpenAI text-embedding-3-small.
 * If they diverge, existing entity embeddings in the DB (generated by direct
 * OpenAI before the v0.1.1 pivot) would no longer be comparable to new query
 * embeddings (generated via OpenRouter), and recall would silently regress.
 *
 * This is a one-shot manual gate, NOT part of CI. To run, first transiently
 * install @ai-sdk/openai (it was removed from project deps in H1), then:
 *
 *   bun add -d @ai-sdk/openai
 *   OPENAI_API_KEY=sk-... OPENROUTER_API_KEY=sk-or-... \
 *     bun run packages/extractor/src/__tests__/embedding-equivalence.smoke.ts
 *   bun remove @ai-sdk/openai
 *
 * Pass criterion: every pair-wise cosine ≥ 0.9999.
 * Fail action: keep embeddings on direct OpenAI as a special case, or wait
 * for OpenRouter to fix.
 *
 * Note: this file is excluded from typecheck via tsconfig.json `exclude`
 * (the `*.smoke.ts` glob). Vitest's `include: ['*.test.ts']` also skips it.
 * That's intentional — smoke tests run only when explicitly invoked.
 */
import { createOpenRouter } from '@openrouter/ai-sdk-provider';
import { embed } from 'ai';

const FIXTURES = [
  'sarah from acme',
  'rust meetup san francisco',
  'send the github link tomorrow morning',
  'CTO at stripe, ships edge runtimes',
  'follow up with marcus about the merge ticket',
  'met dave at re:invent, he heads platform at gitlab',
  'remind me to email the contract by friday',
  'edge workers, wasm, low-latency inference',
  'devconnect istanbul · ethereum stack devs',
  'partnerships lead at vercel, prev shopify',
  'ai sdk + zod structured output',
  'kira chen, founder, anthropic prev',
  'meeting tuesday 9am, agenda is roadmap review',
  'her linkedin handle is sarah-chen-eng',
  'topics: rust, edge runtime, ssr',
  'company observed for the second time tonight',
  'lazy promotion threshold is two observations',
  'turso libsql vector_top_k',
  'haiku 4.5 for relations, sonnet for hard cases',
  'one-paragraph note: she shipped the migration in two days',
];

function cosine(a: number[], b: number[]): number {
  let dot = 0, aMag = 0, bMag = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    aMag += a[i] * a[i];
    bMag += b[i] * b[i];
  }
  const denom = Math.sqrt(aMag) * Math.sqrt(bMag);
  return denom === 0 ? 0 : dot / denom;
}

async function main() {
  const directKey = process.env.OPENAI_API_KEY;
  const routerKey = process.env.OPENROUTER_API_KEY;

  if (!directKey) throw new Error('OPENAI_API_KEY required for the direct-provider side');
  if (!routerKey) throw new Error('OPENROUTER_API_KEY required for the OpenRouter side');

  const direct = await import('@ai-sdk/openai').catch(() => null);
  if (!direct) {
    console.error(
      'ERROR: @ai-sdk/openai was removed from project deps in v0.1.1.\n' +
        'To run this smoke test, install it transiently:\n' +
        '  bun add -d @ai-sdk/openai\n' +
        'Then re-run. Uninstall afterwards.',
    );
    process.exit(1);
  }

  const directModel = direct.openai.textEmbeddingModel('text-embedding-3-small');
  const openrouter = createOpenRouter({ apiKey: routerKey });
  const routerModel = openrouter.textEmbeddingModel('openai/text-embedding-3-small');

  console.log('embedding 20 strings through both providers...\n');

  const results: { fixture: string; cos: number; lenA: number; lenB: number }[] = [];

  for (const fixture of FIXTURES) {
    const [a, b] = await Promise.all([
      embed({ model: directModel, value: fixture }),
      embed({ model: routerModel, value: fixture }),
    ]);
    const cos = cosine(a.embedding, b.embedding);
    results.push({ fixture, cos, lenA: a.embedding.length, lenB: b.embedding.length });
  }

  const THRESHOLD = 0.9999;
  let failed = 0;

  console.log('cos       lenA  lenB  fixture');
  console.log('--------- ----- ----- ----------------------------------------');
  for (const r of results) {
    const flag = r.cos >= THRESHOLD ? '✓' : '✗';
    if (r.cos < THRESHOLD) failed++;
    console.log(
      `${flag} ${r.cos.toFixed(6)} ${String(r.lenA).padStart(5)} ${String(r.lenB).padStart(5)} ${r.fixture.slice(0, 50)}`,
    );
  }

  console.log('');
  if (failed > 0) {
    console.error(
      `FAIL: ${failed}/${results.length} pairs below cosine threshold ${THRESHOLD}.\n` +
        'OpenRouter routes embeddings differently from direct OpenAI for this model.\n' +
        'Option (a): keep OPENROUTER for LLM, route embeddings via direct OPENAI.\n' +
        'Option (b): wait for OpenRouter to fix.\n' +
        'Do NOT merge H1 with diverging embeddings — dev DB recall will regress.',
    );
    process.exit(1);
  }

  console.log(`PASS: all ${results.length} pairs cosine ≥ ${THRESHOLD}. Safe to proceed.`);
}

main().catch((err) => {
  console.error('smoke test crashed:', err);
  process.exit(1);
});
